language: generic

script:
  - test $(grep '<div class="item">' index.html | wc -l) -lte 6 # no more than 6 items
  - test $(grep '<div class="item">' index.html | wc -l) -gte 3  # at least 3 items

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: master
